dist: focal
addons:
  apt:
    packages:
      - libcairo2-dev
      - python-pip-whl
      - python3-ply
      - python3-pycparser
    update: true

sudo: false
cache: pip
language: python
python:
    - "3.5"
    - "3.6"
    - "3.8"
install: pip3 install WeasyPrint Flask cairocffi tox-travis
script: tox -p auto
